class Connection_Error(Exception):
    ...
